### ISSUE TITLE
kriging dim>1 limitation

### ISSUE THREAD

**Issue by jschueller** [openturns/otpod#21]
why is that ?
https://github.com/openturns/otpod/blob/master/otpod/_kriging_pod.py#L99

cc @adumasphi

**Comment by adumasphi** [comment]
Because Kriging and Polynomial Chaos were developed to be used with several inputs parameters : the defect (first column) and other influential variable. In the 1D strategy (only with the defect), it is the error model coming from the regression model that is used to compute the probability, whereas with Kriging and PCE, the distribution (either given or built in) of the other parameters is used to compute the probability.
